/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.biomesohplanty;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class BiomesOhPlantyModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public BiomesOhPlantyModElements() {
		sounds.put(new ResourceLocation("biomes_oh_planty", "cumzone_mus1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "cumzone_mus1")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "calamity"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "calamity")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "no"), new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "no")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "bacon"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "bacon")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "bacon2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "bacon2")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "wait"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "wait")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "pkfire"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "pkfire")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "yharon_p2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "yharon_p2")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "zawarudo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "zawarudo")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "battlefield-cringe-voicelines"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "battlefield-cringe-voicelines")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "snapcoob"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "snapcoob")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "whatthedogdoin"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "whatthedogdoin")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "boopbooboo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "boopbooboo")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "ratialslur"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "ratialslur")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "niconiconii"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "niconiconii")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "blueshell"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "blueshell")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "whywhywhy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "whywhywhy")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "menacing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "menacing")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "theeggannouncement"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "theeggannouncement")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "thatvideo"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "thatvideo")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "failure"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "failure")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "cros"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "cros")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "impasta"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "impasta")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "emergency"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "emergency")));
		sounds.put(new ResourceLocation("biomes_oh_planty", "iamnotoverconfident"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("biomes_oh_planty", "iamnotoverconfident")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("biomes_oh_planty").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == BiomesOhPlantyModElements.ModElement.class)
						elements.add((BiomesOhPlantyModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(BiomesOhPlantyModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new BiomesOhPlantyModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		BiomesOhPlantyMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final BiomesOhPlantyModElements elements;
		protected final int sortid;
		public ModElement(BiomesOhPlantyModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
